# tap repositories and their packages

tap romkatv/powerlevel10k
tap jwbargsten/misc

brew ansible
brew asdf
brew bat
brew defbro
brew flux
brew fzf
brew gawk
brew gpg
brew helm
brew hub
brew kubie
brew kustomize
brew podman
brew powerlevel10k
brew protobuf
brew rbenv
brew ripgrep
brew sops
brew telnet
brew yarn

cask alfred
cask camo-studio
cask dash
cask discord
cask docker
cask google-chrome
cask hammerspoon
cask intellij-idea
cask iterm2
cask karabiner-elements
cask ngrok
cask sequel-ace
cask sublime-text

# App Store applications
appstore 1333542190  1Password 7     (7.9)
appstore 937984704   Amphetamine     (5.2.2)
appstore 967805235   Paste           (3.1.0)
appstore 803453959   Slack           (4.20.0)
appstore 425424353   The Unarchiver  (4.3.3)
appstore 497799835   Xcode           (13.0)
