tap "fluxcd/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "jwbargsten/misc"
tap "norwoodj/tap"
tap "romkatv/powerlevel10k"

brew "ansible"
brew "asdf"
brew "bat"
brew "fzf"
brew "gawk"
brew "git-lfs"
brew "gpg"
brew "helm"
brew "hub"
brew "jq"
brew "kubectx"
brew "kubie"
brew "kustomize"
brew "mas"
brew "podman"
brew "protobuf"
brew "rbenv"
brew "ripgrep"
brew "sops"
brew "telnet"
brew "terraform-docs"
brew "tmux"
brew "wget"
brew "yadm"
brew "yarn"
brew "zsh-syntax-highlighting"

brew "fluxcd/tap/flux"
brew "jwbargsten/misc/defbro"
brew "norwoodj/tap/helm-docs"
brew "romkatv/powerlevel10k/powerlevel10k"

cask "1password-cli"
cask "alfred"
cask "camo-studio"
cask "discord"
cask "docker"
cask "google-chrome"
cask "hammerspoon"
cask "intellij-idea"
cask "iterm2"
cask "kaleidoscope"
cask "karabiner-elements"
cask "ngrok"
cask "parallels"
cask "postman"
cask "sequel-ace"
cask "sublime-text"
cask "1password"

mas "Amphetamine", id: 937984704
mas "Paste", id: 967805235
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
