tap "alexnabokikh/tfsort"
tap "fluxcd/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "jwbargsten/misc"
tap "norwoodj/tap"
tap "romkatv/powerlevel10k"

brew "ansible"
brew "asdf"
brew "bat"
brew "buildpacks/tap/pack"
brew "cmake"
brew "duti"
brew "fzf"
brew "gawk"
brew "gh"
brew "git-lfs"
brew "golangci-lint"
brew "gpg"
brew "gnupg"
brew "helm"
brew "hopenpgp-tools"
brew "hub"
brew "jq"
brew "kubectx"
brew "kubie"
brew "kustomize"
brew "mas"
brew "openssh"
brew "pinentry-mac"
brew "podman"
brew "protobuf"
brew "rbenv"
brew "ripgrep"
brew "sops"
brew "telnet"
brew "terraform-docs"
brew "tfsort"
brew "tmux"
brew "tree"
brew "wget"
brew "yadm"
brew "yarn"
brew "ykman"
brew "yubikey-personalization"
brew "zsh-syntax-highlighting"

brew "fluxcd/tap/flux"
brew "norwoodj/tap/helm-docs"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"

cask "alfred"
cask "camo-studio"
cask "discord"
cask "docker"
cask "fantastical"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "hammerspoon"
cask "intellij-idea"
cask "iterm2"
cask "karabiner-elements"
cask "keybase"
cask "postman"
cask "remarkable"
cask "session-manager-plugin"
cask "sequel-ace"
cask "spaceman"
cask "sublime-text"
cask "synology-drive"
cask "chatgpt"
cask "1password/tap/1password-cli"
cask "1password"

mas "Amphetamine", id: 937984704
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "In Your Face: Meeting Reminder", id: 1476964367
